### ISSUE TITLE
No se puede completar la misión Thalorien Buscalba

### ISSUE THREAD

**Issue by Minarun** [rksmw/Infinitum#2]
Es una de las misiones de la cadena iniciada por la Empunadura Maltrecha, la que te otorga a QuelDelar.
La mision Thalorien Buscalba, ubicada en Queldanas, presenta un error. Lo ideal es que inicie un roleplay con dialogo sobre el cadáver de Thalorien, sin embargo, Thalorien se encuentra levantado y no inicia un dialogo ni activa el trigger de inicio de la misión.
Aqui un video de como debe de iniciar la misión.
https://www.youtube.com/watch?v=yf9fhhOUs1o

**Comment by rksmw** [comment]
Solucionada

**Comment by Minarun** [comment]
La posición del NPC Thalorien esta correcta ahora. El trigger de inicio parece no funcionar.
Ya probe relog, reinicio de wow, borrado de cache.
El problema persiste.

**Comment by rksmw** [comment]
falta actualizar el server , se compilo pero aun falta actualizar

**Comment by rksmw** [comment]
solucionando :)
