### ISSUE TITLE
Bug de habilidad de sacerdote Forma de Sombras.

### ISSUE THREAD

**Issue by Minarun** [rksmw/Infinitum#3]
El hechizo de Forma de las Sombras del sacerdote entra en conflicto reiteradas veces al no poder ser reactivado tras salir del estado al utilizar los hechizos sagrados.
Este problema se ve mas seguido si le agregamos el factor interrupción, ocasionado por ataques enemigos, También entra en conflicto con el global CD de los hechizos sagrados.

**Comment by Minarun** [comment]
![wowscrnshot_020717_145220](https://cloud.githubusercontent.com/assets/25620530/22708654/1c321b76-ed45-11e6-82b6-4ec6179b23a3.jpg)

**Comment by rksmw** [comment]
ok aplicare un cambio en el spellscript , gracias .

**Comment by rksmw** [comment]
una cosa mas , la causa del bug es : utilizar hechizos sagrados en la forma de sombras no es asi ?

**Comment by Minarun** [comment]
Si.
El caso mas comun es usar Rezo de Alivio en forma de sombras e intentar volver a activarlo.

**Comment by rksmw** [comment]
corrección aplicada :)
