### ISSUE TITLE
Mision: El lider prodigo

### ISSUE THREAD

**Issue by Minarun** [rksmw/Infinitum#4]
En la cadena de misiones que inicia Mathias Lehner en Corona de Hielo, El lider Prodigo, aquella donde te transformas en Arthas y debes matar y revivir a 100 soldados en no muertos.
La habilidad Rajar Alma del botón 2 no funciona, pide un objetivo, a pesar que esta frente a el y marcado.

**Comment by rksmw** [comment]
por favor pon la id de la quest

**Comment by Minarun** [comment]
Quest ID : 13236
http://es.wowhead.com/quest=13236/el-ejercito-de-los-malditos

**Comment by rksmw** [comment]
corrección agregada
