### ISSUE TITLE
Mision purificacion de quel´delar

### ISSUE THREAD

**Issue by berales** [rksmw/Infinitum#5]
en la mision al tomarla, los celadores al hablar con ellos te dan la opcion para teleportarte al lugar donde debes purificarla en la fuente del sol, al hablar con ellos no te dan la opcion de que te teleporten. adjunto la informacion de wowhead  http://es.wowhead.com/npc=37523/celador-de-la-fuente-del-sol ese es el celador y la mision es http://es.wowhead.com/quest=24596/la-purificacion-de-queldelar  mando pantallazos.

![wowscrnshot_021017_152912](https://cloud.githubusercontent.com/assets/25673296/22839174/296c2480-efa7-11e6-89c0-00654e0f9add.jpg)
![wowscrnshot_021017_152908](https://cloud.githubusercontent.com/assets/25673296/22839175/297163aa-efa7-11e6-8c81-2e021dcecbc2.jpg)

Atte Pablo

**Comment by rksmw** [comment]
solucionando ... la corrección se aplicara en la próxima actualización
